In [1]:
import numpy as np
import json
import matplotlib.pyplot as plt
from time import time
import os

dir = os.getcwd()
datadir = os.path.join(dir, 'vessel_data/CSAD')
filepath = os.path.join(datadir, [file for file in os.listdir(datadir) if file.endswith('.json')][0])

In [2]:
def timeit(func):
    # Function for calculating execution time.
    def wrapper(*args, **kwargs):
        start = time()
        result = func(*args, **kwargs)
        end = time()
        print(f"Execution time of '{func.__name__}': {end - start}")
        return result
    return wrapper

In [3]:
# Get the parameters from CSAD

with open(filepath, 'r') as f:
    data = json.load(f)



Mrb = np.asarray(data['MRB'])
A = np.asarray(data['A'])
B = np.asarray(data['B'])
C = np.asarray(data['C'])
freqs = np.asarray(data['freqs'])
headings = np.asarray(data['headings'])
Bv = np.asarray(data['Bv'])
# Store RAOs as complex values -> magnitude as real value and phase as imaginary
forceRAO = np.asarray(data['forceRAO']['amp'])[:, :, :, 0] + np.asarray(data['forceRAO']['phase'])[:, :, :, 0]*1j
motionRAO = np.asarray(data['motionRAO']['amp'])[:, :, :, 0] + np.asarray(data['motionRAO']['phase'])[:, :, :, 0]*1j
QTFs = np.asarray(data['driftfrc']['amp'])[:, :, :, 0]
QTFs[0].shape

(36, 36)

In [4]:
from numpy import dtype


@timeit
def full_qtf(qtfs, headings, freqs, wave_freqs, dof=0):
    # Generate full QTF by Newman approximation
    num_headings = len(headings)
    num_freq = len(wave_freqs)
    freq_indices = [np.argmin(np.abs(freqs - w)) for w in wave_freqs]
    Q = np.zeros((num_headings, num_freq, num_freq))
    Qjk = qtfs[dof].copy()
    for i in range(num_headings):
        for j, freq_j in enumerate(freq_indices):
            Q_j = Qjk[freq_j, i]
            for k, freq_k in enumerate(freq_indices):
                Q_k = Qjk[freq_k, i]
                Q[i, j, k] = 0.5*(Q_j + Q_k)
    return Q

@timeit
def full_qtf_alt(qtfs, headings, freqs, wave_freqs, dof=0):
    num_headings = len(headings)
    num_freq = len(wave_freqs)
    freq_indices = [np.argmin(np.abs(freqs - w)) for w in wave_freqs]
    Q = np.zeros((num_headings, num_freq, num_freq))
    Qdiag = qtfs[dof, [freq_indices], :].copy()
    for i in range(len(headings)):
        Q[i] = 0.5*(Qdiag[0, :, i, None] + Qdiag[0, :, i])
    return Q

N = 100 # Number of wave frequencies
wave_freqs = np.linspace(0.1, 3.14, N, endpoint=False)
# wave_freqs = freqs

print(f"Result diff: {np.sum(full_qtf_alt(QTFs, headings, freqs, wave_freqs, dof=0) - full_qtf(QTFs, headings, freqs, wave_freqs, dof=0))}")

@timeit
def full_qtf_6dof():
    Qd_surge = full_qtf(QTFs, headings, freqs, wave_freqs, dof=0)
    Qd_sway = full_qtf(QTFs, headings, freqs, wave_freqs, dof=1)
    Qd_heave = full_qtf(QTFs, headings, freqs, wave_freqs, dof=2)
    Qd_roll = full_qtf(QTFs, headings, freqs, wave_freqs, dof=3)
    Qd_pitch = full_qtf(QTFs, headings, freqs, wave_freqs, dof=4)
    Qd_yaw = full_qtf(QTFs, headings, freqs, wave_freqs, dof=5)
    return np.vstack([[Qd_surge], [Qd_sway], [Qd_heave], [Qd_roll], [Qd_pitch], [Qd_yaw]])

Qd = full_qtf_6dof()

Execution time of 'full_qtf_alt': 0.005987405776977539
Execution time of 'full_qtf': 0.41846394538879395
Result diff: 0.0
Execution time of 'full_qtf': 0.3983149528503418
Execution time of 'full_qtf': 0.33846211433410645
Execution time of 'full_qtf': 0.29185914993286133
Execution time of 'full_qtf': 0.2432723045349121
Execution time of 'full_qtf': 0.22981595993041992
Execution time of 'full_qtf': 0.22873377799987793
Execution time of 'full_qtf_6dof': 1.7467472553253174


In [5]:
np.diagonal(Qd[0, 0])

array([ 3.17367367e-01,  3.17367367e-01,  5.94219942e+00,  5.94219942e+00,
        5.94219942e+00,  1.38092320e+01,  1.38092320e+01,  4.01660520e+01,
        6.51061525e+01,  8.24138033e+01,  1.10875333e+02,  1.18135315e+02,
        7.74535392e+01, -1.21645553e+02, -3.62628882e+02, -7.99327759e+02,
       -2.87048425e+03, -5.10007372e+03, -8.77913026e+03, -8.77913026e+03,
       -1.46134842e+04, -2.31341704e+04, -3.35546646e+04, -3.35546646e+04,
       -4.07410039e+04, -4.07410039e+04, -3.31479050e+04, -3.31479050e+04,
       -3.16543641e+03, -3.16543641e+03,  1.42020688e+04,  1.42020688e+04,
        1.42020688e+04, -4.97593281e+03, -4.97593281e+03, -4.97593281e+03,
       -4.97593281e+03, -2.74979941e+03, -2.74979941e+03, -2.74979941e+03,
       -2.74979941e+03,  8.36256656e+03,  8.36256656e+03,  8.36256656e+03,
        8.36256656e+03,  8.36256656e+03,  1.67735270e+04,  1.67735270e+04,
        1.67735270e+04,  1.67735270e+04,  1.67735270e+04,  1.67735270e+04,
        1.67735270e+04,  

In [6]:
QTFs[0].shape

(36, 36)

In [7]:
Qd_surge_heading0_diag = QTFs[0, :, 0]

In [8]:
Qd_surge_heading0 = 0.5*(Qd_surge_heading0_diag[:, None] + Qd_surge_heading0_diag)

In [9]:
freqs

array([0.1047198, 0.2094395, 0.2513274, 0.3141593, 0.330694 , 0.3490659,
       0.3695991, 0.3926991, 0.4053668, 0.418879 , 0.4333231, 0.448799 ,
       0.4654211, 0.483322 , 0.5026549, 0.5235988, 0.5463639, 0.5711987,
       0.5983986, 0.6283185, 0.6613879, 0.6981317, 0.7391983, 0.7853982,
       0.8377581, 0.8975979, 0.9666439, 1.047198 , 1.142397 , 1.256637 ,
       1.396263 , 1.570796 , 1.795196 , 2.094395 , 2.513274 , 3.141593 ])

In [10]:
from wave_loads import WaveLoad

In [11]:
amps = np.linspace(0, 3, N)
phase = np.random.random(N)*2*np.pi



waveload = WaveLoad(amps, wave_freqs, phase, headings, 0)
waveload._full_qtf_6dof(headings, freqs, QTFs)

Execution time of _full_qtf_6dof: 0.0219


array([[[[ 3.17367367e-01,  3.17367367e-01,  3.12978340e+00, ...,
           3.94089646e+04,  3.94089646e+04,  3.94089646e+04],
         [ 3.17367367e-01,  3.17367367e-01,  3.12978340e+00, ...,
           3.94089646e+04,  3.94089646e+04,  3.94089646e+04],
         [ 3.12978340e+00,  3.12978340e+00,  5.94219942e+00, ...,
           3.94117770e+04,  3.94117770e+04,  3.94117770e+04],
         ...,
         [ 3.94089646e+04,  3.94089646e+04,  3.94117770e+04, ...,
           7.88176118e+04,  7.88176118e+04,  7.88176118e+04],
         [ 3.94089646e+04,  3.94089646e+04,  3.94117770e+04, ...,
           7.88176118e+04,  7.88176118e+04,  7.88176118e+04],
         [ 3.94089646e+04,  3.94089646e+04,  3.94117770e+04, ...,
           7.88176118e+04,  7.88176118e+04,  7.88176118e+04]],

        [[ 3.25684763e-01,  3.25684763e-01,  3.37459101e+00, ...,
           3.84563115e+04,  3.84563115e+04,  3.84563115e+04],
         [ 3.25684763e-01,  3.25684763e-01,  3.37459101e+00, ...,
           3.84563115e

In [12]:
# Implempentation in wave loads module corresponds to that done in this notebook
# However - the speed is much faster in the wave module function.
# about 50 times faster actually.
np.sum(full_qtf_6dof() - waveload._full_qtf_6dof(headings, freqs, QTFs))

Execution time of 'full_qtf': 0.37677693367004395
Execution time of 'full_qtf': 0.4651942253112793
Execution time of 'full_qtf': 0.3706068992614746
Execution time of 'full_qtf': 0.26431775093078613
Execution time of 'full_qtf': 0.2939791679382324
Execution time of 'full_qtf': 0.42686939239501953
Execution time of 'full_qtf_6dof': 2.2336432933807373
Execution time of _full_qtf_6dof: 0.0389


0.0

In [13]:
2.23/0.04

55.75